name: preview_on_dispatch

on: workflow_dispatch

concurrency:
  group: ci-preview-${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  preview_backend:
    uses: jalantechnologies/platform-github/.github/workflows/kube.yml@v2.5
    with:
      app_name: boilerplate-website-backend
      app_env: preview
      app_hostname: '{1}-backend.preview.platform.jalantechnologies.com'
      branch: ${{ github.event.ref }}
      build_context: 'api'
      build_args: |
        CI=true
        NODE_ENV=production
      deploy_root: 'lib/kube/backend'
      steps: 'deploy'
    secrets:
      docker_registry: docker-registry.platform.jalantechnologies.com/boilerplate-website
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      doppler_token: ${{ secrets.DOPPLER_PREVIEW_TOKEN }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}

  preview_frontend:
    uses: jalantechnologies/platform-github/.github/workflows/kube.yml@v2.5
    needs: 'preview_backend'
    with:
      app_name: boilerplate-website-frontend
      app_env: preview
      app_hostname: '{1}-website.preview.platform.jalantechnologies.com'
      branch: ${{ github.event.ref }}
      build_args: |
        CI=true
        NODE_ENV=production
        STRAPI_API_URL=${{ needs.preview_backend.outputs.deploy_url }}
        STRAPI_TOKEN=5e7a70034ee3872391ecc4f8d58862239fd5275e3e4c6ee33a1fbd0d5b6866477123167b94aa1e7607cb073528b3e10068f5a681242476f8100d23f47f9297e1221e89f562a7e1b8049b991b47333b373e3219794c0c4b89a17a85bd2e4f0bfcdfcbc94665700b9a063cf3f60797f9cd26bac0c5aa2a215f29f74a675b8aac8a
      deploy_root: 'lib/kube/frontend'
      steps: 'deploy'
    secrets:
      docker_registry: docker-registry.platform.jalantechnologies.com/boilerplate-website
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      do_cluster_id: ${{ secrets.DO_CLUSTER_ID }}
